# Author: Li Yuanming
# Email: yuanmingleee@gmail.com
# Date: May 26, 2022

name: "resnet"
backend: "python"

instance_group [{
  count: 1
  kind: KIND_GPU
  gpus: [ 0 ]
}]

parameters: {
  key: "EXECUTION_ENV_PATH"
  value: {string_value: "$$TRITON_MODEL_DIRECTORY/../my-pytorch.tar.gz"}
}