name: "IMG_CLASSIFICATION_TORCH"
version: 0.1
active_learning:
  strategy:
    type: "LeastConfidence"
    model:
      name: "resnet18"
      hub: "pytorch/vision:v0.10.0"
      batch_size: 1
      device: "cpu"
  al_worker:
    protocol: "grpc"
    host: "0.0.0.0"
    port: 60035
    replicas: 1

