name: "IMG_CLASSIFICATION"
version: 0.1
active_learning:
  budget: 10
  strategy:
    type: "LeastConfidence"
    infer_model:
      name: "resnet"
      type: torch_hub
      hub_name: "pytorch/vision:release/0.12"
      model: "resnet18"
      conda_env: my-pytorch
      batch_size: 4
      input:
        - data_type: TYPE_FP32
          dims: [ -1, 3, 224, 224 ]
      output:
        - data_type: TYPE_FP32
          dims: [ -1, 1000 ]
      instance_group:
        - count: 1
          kind: KIND_GPU
  al_server:
    url: "54.251.31.100:8900"
    worker:
      type: docker
      docker_repo: "nvcr.io/nvidia/tritonserver"
      tag: "22.03-pyt-python-py3"
      docker_kwargs:
        auto_remove: false
